"""
Simulated Annealing optimizer for COSMIC mission schedule optimisation.
"""

import numpy as np
import random
from typing import List, Tuple

from me_roadmap.optimization.cost_model import roadmap_cost


def optimize_schedule(
    readiness_array: np.ndarray,
    dependency_array: np.ndarray,
    learning_rate_array: np.ndarray,
    utilization_array: np.ndarray,
    n_iterations: int = 5000,
    initial_temp: float = 1e12,
    cooling_rate: float = 0.995,
    verbose: bool = True,
) -> Tuple[List[int], float]:
    """Optimise the mission execution order using Simulated Annealing.

    Neighbour states are generated by swapping two randomly chosen missions.
    A re-heat is applied when the temperature drops below 1e-5 to help escape
    local minima.

    Parameters:
        readiness_array: (num_missions, num_capabilities).
        dependency_array: (num_missions, num_capabilities).
        learning_rate_array: (num_missions, num_capabilities) – percentages.
        utilization_array: (num_missions, num_capabilities).
        n_iterations: total number of SA iterations.
        initial_temp: starting temperature.
        cooling_rate: multiplicative cooling factor applied each iteration.
        verbose: if True, prints progress updates when a new best is found.

    Returns:
        Tuple[List[int], float]: (best_order, best_cost).
            best_order is a list of mission indices in the optimal execution sequence.
    """
    num_missions = dependency_array.shape[0]

    current_order = list(range(num_missions))
    random.shuffle(current_order)
    current_cost = roadmap_cost(
        current_order, readiness_array, dependency_array, learning_rate_array, utilization_array
    )

    best_order = list(current_order)
    best_cost = current_cost
    temperature = initial_temp

    if verbose:
        print(f"Initial Cost: {current_cost:.4f}")

    for i in range(n_iterations):
        new_order = list(current_order)
        idx1, idx2 = random.sample(range(num_missions), 2)
        new_order[idx1], new_order[idx2] = new_order[idx2], new_order[idx1]

        new_cost = roadmap_cost(
            new_order, readiness_array, dependency_array, learning_rate_array, utilization_array
        )
        delta = new_cost - current_cost

        if delta < 0 or random.random() < np.exp(-delta / max(temperature, 1e-300)):
            current_order = new_order
            current_cost = new_cost

            if current_cost < best_cost:
                best_cost = current_cost
                best_order = list(current_order)
                if verbose:
                    print(f"Iteration {i}: New Best Cost = {best_cost:.4f}")

        temperature *= cooling_rate
        if temperature < 1e-5:
            temperature = initial_temp * 0.1  # partial re-heat

    return best_order, best_cost
